name: validate

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
    paths:
      - '*/PKGBUILD'

jobs:
  find-packages:
    name: Find updated packages
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.find-packages.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Find updated packages
        id: find-packages
        run: |
          #!/usr/bin/env bash
          set -euxo pipefail

          changed=$(git diff --name-only origin/main "origin/${GITHUB_HEAD_REF}" "*PKGBUILD" | xargs -r dirname)
          if [ -z "$changed" ]; then
            echo "::error::PKGBUILD has no changes with origin/main, but the workflow was triggered by a PKGBUILD change"
            exit 1
          fi

          echo "packages=$(echo "$changed" | jq -Rnc '[inputs]')" >> "$GITHUB_OUTPUT"

  validate:
    name: ${{ matrix.package }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    needs: find-packages
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.find-packages.outputs.packages) }}
        arch:
          - x86_64
          - aarch64
        include:
          - arch: x86_64
            runner: ubuntu-latest
            image: docker.io/library/archlinux:base-devel
            update_metadata: true

          - arch: aarch64
            runner: ubuntu-24.04-arm
            image: docker.io/menci/archlinuxarm:base-devel
            update_metadata: false

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Build and validate
        uses: ./.github/actions/pkgbuild
        with:
          pkgname: ${{ matrix.package }}
          image: ${{ matrix.image }}
          update_metadata: ${{ matrix.update_metadata }}
          base_sha: ${{ github.event.pull_request.base.sha }}

      - name: Upload regenerated metadata
        if: matrix.update_metadata
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ matrix.package }}
          path: ${{ matrix.package }}
          include-hidden-files: true
          if-no-files-found: error

  commit:
    name: Commit regenerated metadata
    runs-on: ubuntu-latest
    needs: validate
    concurrency:
      group: commit-metadata-${{ github.ref }}
      cancel-in-progress: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Download regenerated metadata
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1

      - name: Commit regenerated metadata
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          branch: ${{ github.head_ref }}
          file_pattern: '*/PKGBUILD */.SRCINFO'
